[profile.default]
slow-timeout = { period = "30s", terminate-after = 2, grace-period = "5s" }

# Performance tests should run serially to avoid CPU contention affecting timing measurements
[[profile.default.overrides]]
filter = 'test(test_hash_lookup_vs_linear_search_simulation)'
threads-required = 'num-cpus'

# LSP integration tests must run serially because each test starts its own LSP server
[[profile.default.overrides]]
filter = 'test(#test_document_highlight_state_variable|test_robotapi_pattern_matching|test_metta_goto_definition|test_metta_hover)'
threads-required = 1
