name: Build and Test
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
  F1R3FLY_REPO_URL: https://github.com/f1R3FLY-io/f1r3fly.git
jobs:
  build-and-test:
    name: Build and Test against ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Install RNode dependencies (Ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        # https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html#Ubuntu+and+other+Debian-based+distributions
        echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
        echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
        curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk git curl unzip make cmake libtool autoconf ghc cabal-install protobuf-compiler sbt jflex
        cabal update
        cabal install alex happy
        cabal install BNFC
        # Set JAVA_HOME for JDK 11
        echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
        echo "/usr/lib/jvm/java-11-openjdk-amd64/bin" >> $GITHUB_PATH
    - name: Install RNode dependencies (macOS)
      if: startsWith(matrix.os, 'macos')
      run: |
        brew update
        brew install openjdk@11 git sbt curl unzip make cmake libtool autoconf protobuf jflex bnfc
        # Set JAVA_HOME for JDK 11
        sudo ln -sfn /opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk
        echo "JAVA_HOME=/opt/homebrew/opt/openjdk@11" >> $GITHUB_ENV
        echo "/opt/homebrew/opt/openjdk@11/bin" >> $GITHUB_PATH
    - name: Install RNode dependencies (Windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        # Install Chocolatey if not present
        if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        }
        choco install -y openjdk11 git sbt curl unzip cmake mingw protoc haskell-stack msys2
        # Set JAVA_HOME for JDK 11
        $JAVA_HOME = (Get-Command java | Select-Object -ExpandProperty Source | Split-Path -Parent | Split-Path -Parent)
        Write-Output "JAVA_HOME=$JAVA_HOME" >> $env:GITHUB_ENV
        Write-Output "$JAVA_HOME\bin" >> $env:GITHUB_PATH
        # Install make and autoconf via MSYS2
        C:\tools\msys64\usr\bin\pacman.exe -S --noconfirm make autoconf
        # ------------------------- #
        # Use Stack to install BNFC #
        # ------------------------- #
        stack install BNFC
        stack path --local-pkg-db
        stack exec -- which bnfc
        # Define the Stack bin directory
        $stackBin = "$env:APPDATA\local\bin"
        Write-Output "$stackBin" >> $env:GITHUB_PATH
        # Get the current system PATH
        $currentPath = [Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::Machine)
        # Check if the Stack bin directory is already in PATH
        if ($currentPath -notlike "*$stackBin*") {
            Write-Host "Adding $stackBin to system PATH..."
            # Append the Stack bin directory to PATH
            [Environment]::SetEnvironmentVariable(
                "Path",
                "$currentPath;$stackBin",
                [EnvironmentVariableTarget]::Machine
            )
            Write-Host "PATH updated successfully."
        } else {
            Write-Host "Stack bin directory is already in PATH."
        }
        bnfc --version
        # ------------------------------------------- #
        # Install JFlex (this is a bit more involved) #
        # ------------------------------------------- #
        $jflexVersion = "1.9.1"  # Replace with desired version or fetch dynamically
        $jflexUrl = "https://github.com/jflex-de/jflex/releases/download/v$jflexVersion/jflex-$jflexVersion.zip"
        $installDir = "C:\jflex"
        $zipFile = "$env:TEMP\jflex-$jflexVersion.zip"
        # Create installation directory
        New-Item -ItemType Directory -Force -Path $installDir | Out-Null
        # Download JFlex ZIP
        Write-Host "Downloading JFlex v$jflexVersion..."
        Invoke-WebRequest -Uri $jflexUrl -OutFile $zipFile
        # Extract ZIP
        Write-Host "Extracting JFlex to $installDir..."
        Expand-Archive -Path $zipFile -DestinationPath $installDir -Force
        # Add JFlex bin to system PATH
        $jflexBin = "$installDir\jflex-$jflexVersion\bin"
        Write-Output "$jflexBin" >> $env:GITHUB_PATH
        $currentPath = [Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::Machine)
        if ($currentPath -notlike "*$jflexBin*") {
            Write-Host "Adding JFlex to system PATH..."
            [Environment]::SetEnvironmentVariable(
                "Path",
                "$currentPath;$jflexBin",
                [EnvironmentVariableTarget]::Machine
            )
        }
        # Clean up
        Remove-Item -Path $zipFile -Force
        Write-Host "JFlex installation complete."
        # Verify installation
        Write-Host "Verifying JFlex installation..."
        $jflexPath = "$jflexBin\jflex.bat"
        if (Test-Path $jflexPath) {
            & $jflexPath --version
        } else {
            Write-Host "Error: JFlex not found at $jflexPath"
        }
    - name: Verify protoc and BNFC
      run: |
        if ! command -v protoc >/dev/null 2>&1; then
          echo "Error: protoc not installed correctly." >&2
          exit 1
        fi
        if ! bnfc --version >/dev/null 2>&1; then
          echo "Error: BNFC not installed correctly or not executable." >&2
          bnfc --version
          file /usr/local/bin/bnfc || true
          exit 1
        fi
        # Verify JDK 11
        if ! java -version 2>&1 | grep -q "11\."; then
          echo "Error: JDK 11 is not being used." >&2
          java -version
          exit 1
        fi
      shell: bash
    - name: Java Info
      run: |
        which java
        java -version
      shell: bash
    - name: Cache RNode artifacts
      uses: actions/cache@v4
      id: cache-rnode
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          f1r3fly/node/target/universal/stage/
        key: ${{ runner.os }}-rnode-${{ hashFiles('f1r3fly/build.sbt', 'f1r3fly/project/*.sbt', 'f1r3fly/project/build.properties') }}-${{ env.F1R3FLY_COMMIT_HASH }}
        restore-keys: |
          ${{ runner.os }}-rnode-
    - name: Clone F1R3FLY repository
      if: steps.cache-rnode.outputs.cache-hit != 'true'
      run: |
        git clone --single-branch --branch main --depth 1 ${{ env.F1R3FLY_REPO_URL }} f1r3fly
        if [ $? -ne 0 ]; then
          echo "Error: Failed to clone F1R3FLY repository." >&2
          exit 1
        fi
        # Store commit hash for cache key
        cd f1r3fly
        echo "F1R3FLY_COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
        cd ..
      shell: bash
    - name: Build RNode
      if: steps.cache-rnode.outputs.cache-hit != 'true'
      run: |
        cd f1r3fly
        sbt -mem 8192 -Dsbt.supershell=false -java-home "${JAVA_HOME}" -J-Xmx8G -J-Xms2G -J-XX:MaxMetaspaceSize=1G -J-XX:+UseG1GC "set scalaVersion := \"2.12.15\"" clean bnfc:generate compile stage
        cd ..
      shell: bash
    - name: Start RNode in standalone mode
      run: |
        RNODE_BIN="$PWD/f1r3fly/node/target/universal/stage/bin/rnode"
        if [ ! -x "$RNODE_BIN" ]; then
          echo "Error: RNode executable not found." >&2
          exit 1
        fi
        # Start RNode in background
        "$RNODE_BIN" run -s &
        RNODE_PID=$!
        # Wait for RNode to start
        for i in {1..30}; do
          if curl -s http://localhost:40403/status >/dev/null; then
            echo "RNode started successfully"
            break
          fi
          echo "Waiting for RNode to start..."
          sleep 5
        done
        if ! curl -s http://localhost:40403/status >/dev/null; then
          echo "Error: RNode failed to start." >&2
          exit 1
        fi
      shell: bash
      env:
        RNODE_PID: ""
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Stop RNode
      if: always()
      run: |
        if [ -n "${RNODE_PID}" ]; then
          kill $RNODE_PID || true
        fi
      shell: bash
