name: Test CI
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
  F1R3FLY_REPO_URL: https://github.com/f1R3FLY-io/f1r3fly.git
jobs:
  build-and-test:
    name: Build and Test against ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # - windows-latest
          - macos-latest
          - ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: Install protoc (Ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    - name: Install protoc (macOS)
      if: startsWith(matrix.os, 'macos')
      run: |
        brew install protobuf
    - name: Install protoc (Windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        choco install protoc
    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Install RNode dependencies (Ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        # https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html#Ubuntu+and+other+Debian-based+distributions
        echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
        echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
        curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk git curl unzip make cmake libtool autoconf ghc cabal-install protobuf-compiler sbt jflex
        cabal update
        cabal install alex happy
        cabal install BNFC
        # Set JAVA_HOME for JDK 11
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        export PATH="/usr/lib/jvm/java-11-openjdk-amd64/bin:$PATH"
        echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
        echo "/usr/lib/jvm/java-11-openjdk-amd64/bin" >> $GITHUB_PATH
    - name: Install RNode dependencies (macOS)
      if: startsWith(matrix.os, 'macos')
      run: |
        brew update
        brew install openjdk@11 git sbt curl unzip make cmake libtool autoconf protobuf jflex bnfc
        # Set JAVA_HOME for JDK 11
        sudo ln -sfn /opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk
        export JAVA_HOME="/opt/homebrew/opt/openjdk@11"
        export PATH="$JAVA_HOME/bin:$PATH"
        echo "JAVA_HOME=/usr/local/opt/openjdk@11" >> $GITHUB_ENV
        echo "$JAVA_HOME/bin" >> $GITHUB_PATH
    - name: Install RNode dependencies (Windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        # Install Chocolatey if not present
        if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        }
        choco install -y openjdk11 git sbt curl unzip cmake mingw protoc
        # Install make and autoconf via MSYS2
        choco install -y msys2
        C:\tools\msys64\usr\bin\pacman.exe -S --noconfirm make autoconf
        # Set JAVA_HOME for JDK 11
        $JAVA_HOME = (Get-Command java | Select-Object -ExpandProperty Source | Split-Path -Parent | Split-Path -Parent)
        Write-Output "JAVA_HOME=$JAVA_HOME" >> $env:GITHUB_ENV
        Write-Output "$JAVA_HOME\bin" >> $env:GITHUB_PATH
        # BNFC: Manual download required
        Write-Output "BNFC 2.9.5 must be manually downloaded from https://github.com/BNFC/bnfc/releases/download/2.9.5/bnfc-2.9.5-windows-x86_64.exe"
        Write-Output "Place it in C:\ProgramData\bnfc\bnfc.exe and add C:\ProgramData\bnfc to PATH."
        Write-Output "Warning: Native Windows builds may fail. If issues occur, consider using WSL or a Ubuntu VM (Hyper-V)."
        # Create a dummy BNFC to allow the workflow to proceed (replace with actual BNFC in production)
        New-Item -ItemType Directory -Force -Path "C:\ProgramData\bnfc"
        Set-Content -Path "C:\ProgramData\bnfc\bnfc.exe" -Value "echo BNFC placeholder"
        $env:PATH += ";C:\ProgramData\bnfc;C:\tools\msys64\usr\bin"
    - name: Verify protoc and BNFC
      run: |
        if ! command -v protoc >/dev/null 2>&1; then
          echo "Error: protoc not installed correctly." >&2
          exit 1
        fi
        if ! bnfc --version >/dev/null 2>&1; then
          echo "Error: BNFC not installed correctly or not executable." >&2
          bnfc --version
          file /usr/local/bin/bnfc || true
          exit 1
        fi
        # Verify JDK 11
        if ! java -version 2>&1 | grep -q "11\."; then
          echo "Error: JDK 11 is not being used." >&2
          java -version
          exit 1
        fi
      shell: bash
    - name: Cache RNode artifacts
      uses: actions/cache@v4
      id: cache-rnode
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          f1r3fly/node/target/universal/stage/
        key: ${{ runner.os }}-rnode-${{ hashFiles('f1r3fly/build.sbt', 'f1r3fly/project/*.sbt', 'f1r3fly/project/build.properties') }}-${{ env.F1R3FLY_COMMIT_HASH }}
        restore-keys: |
          ${{ runner.os }}-rnode-
    - name: Clone F1R3FLY repository
      run: |
        git clone --single-branch --branch main --depth 1 ${{ env.F1R3FLY_REPO_URL }} f1r3fly
        if [ $? -ne 0 ]; then
          echo "Error: Failed to clone F1R3FLY repository." >&2
          exit 1
        fi
        # Store commit hash for cache key
        cd f1r3fly
        echo "F1R3FLY_COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
        cd ..
      shell: bash
    - name: Build RNode
      if: steps.cache-rnode.outputs.cache-hit != 'true'
      run: |
        cd f1r3fly
        sbt -mem 8192 -Dsbt.supershell=false -java-home "${JAVA_HOME}" -J-Xmx8G -J-Xms2G -J-XX:MaxMetaspaceSize=1G -J-XX:+UseG1GC "set scalaVersion := \"2.12.15\"" clean bnfc:generate compile stage
        cd ..
      shell: bash
    - name: Start RNode in standalone mode
      run: |
        RNODE_BIN="$PWD/f1r3fly/node/target/universal/stage/bin/rnode"
        if [ ! -x "$RNODE_BIN" ]; then
          echo "Error: RNode executable not found." >&2
          exit 1
        fi
        # Start RNode in background
        "$RNODE_BIN" run -s
        RNODE_PID=$!
        # Wait for RNode to start
        for i in {1..30}; do
          if curl -s http://localhost:40403/status >/dev/null; then
            echo "RNode started successfully"
            break
          fi
          echo "Waiting for RNode to start..."
          sleep 5
        done
        if ! curl -s http://localhost:40403/status >/dev/null; then
          echo "Error: RNode failed to start." >&2
          exit 1
        fi
      shell: bash
      env:
        RNODE_PID: ""
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Stop RNode
      if: always()
      run: |
        if [ -n "${RNODE_PID}" ]; then
          kill $RNODE_PID || true
        fi
      shell: bash
